# Generated by Django 2.2 on 2019-04-29 19:27

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='user',
            field=models.ManyToManyField(related_name='team_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 29, 19, 27, 12, 859754, tzinfo=utc)),
        ),
    ]
