# Generated by Django 2.2 on 2019-04-29 19:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20190429_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
