# Generated by Django 2.2 on 2019-05-04 04:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20190504_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
