# Generated by Django 2.2 on 2019-05-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20190506_0715'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitelink',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
