# Generated by Django 2.2 on 2019-05-11 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_invitelink_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitelink',
            name='email',
        ),
        migrations.RemoveField(
            model_name='invitelinkusers',
            name='user',
        ),
        migrations.AddField(
            model_name='invitelinkusers',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
