# Generated by Django 2.2 on 2019-05-14 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20190511_1716'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postrecomment',
            options={'get_latest_by': ['-created_on']},
        ),
    ]
