# Generated by Django 2.2 on 2019-05-14 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20190514_0518'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postrecomment',
            options={'get_latest_by': ['created_on']},
        ),
    ]
