# Generated by Django 2.2 on 2019-05-14 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20190514_0528'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postrecomment',
            options={'ordering': ['created_on']},
        ),
    ]
