# Generated by Django 2.2 on 2019-05-14 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_auto_20190514_0534'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postrecomment',
            options={'ordering': ['-created_on']},
        ),
    ]
