# Generated by Django 2.2 on 2019-05-15 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_auto_20190515_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='subgroup',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.Team'),
        ),
    ]
