# Generated by Django 2.2 on 2019-05-16 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_subgroup_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subgroup',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
