# Generated by Django 2.2 on 2019-05-17 15:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0020_posttaggeduser'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='posttaggeduser',
            unique_together={('user', 'post')},
        ),
    ]
