# Generated by Django 2.2 on 2019-05-23 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_auto_20190517_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='subgroup',
            name='pic',
            field=models.FileField(blank=True, null=True, upload_to='subgroup/'),
        ),
        migrations.AddField(
            model_name='team',
            name='pic',
            field=models.FileField(blank=True, null=True, upload_to='group/'),
        ),
    ]
