# Generated by Django 2.2 on 2019-05-23 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_auto_20190523_0704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subgroup',
            name='pic',
        ),
    ]
