# Generated by Django 2.2 on 2019-05-25 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_remove_subgroup_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='post',
            field=models.ManyToManyField(blank=True, null=True, to='posts.Post'),
        ),
    ]
