# Generated by Django 2.2 on 2019-05-25 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0024_notification_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='post',
            field=models.ManyToManyField(to='posts.Post'),
        ),
    ]
