# Generated by Django 2.2 on 2019-05-23 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190523_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.FileField(blank=True, null=True, upload_to='pics/'),
        ),
    ]
